FROM sebastianluen/lean:latest

MAINTAINER Sebastian Lueneburg <sebastian.lueneburg@gmail.com>

COPY ./ToolBox/bin/Release/ /repos/quantconnect/Lean/ToolBox/bin/Release/
RUN rm -f /repos/quantconnect/Lean/ToolBox/bin/Release/log.txt

WORKDIR /repos/quantconnect/Lean/ToolBox/bin/Release

ENTRYPOINT [ "dotnet", "QuantConnect.ToolBox.dll" ]
