syntax = "proto3";
package QuantConnect.Algorithm.CSharp.Core.IO;

option csharp_namespace = "QuantConnect.Algorithm.CSharp.Core.IO";

enum ChannelPb {
    HB = 0;
    TARGET_PORTFOLIO = 1;
    ECHO = 2;
    TERMINATE = 3;
    STRESS_TEST_DS = 4;
    CMD_FETCH_TARGET_PORTFOLIO = 5;
    CMD_CANCEL_OID = 6;
    KALMAN_INIT = 7;
    CMD_CFG_OVERRIDE = 8;
    REQUEST_SSVI_CALIBRATION = 9;
    REQUEST_PF_RISK_SCENARIOS = 10;
    REQUEST_CACHE_IVS = 11;
    REQUEST_LEAN_PRICE2IV = 12;
}

enum ActionPb {
    SUBSCRIBE = 0;
    UNSUBSCRIBE = 1;
}

message MessagePb {

  ChannelPb channel = 1;
  string id = 2;
  ActionPb action = 3;
  bytes payload = 4;
}

message HoldingPb {

  string symbol = 1;
  float quantity = 2;
  SecurityTypePb security_type = 3;
}

message OptionQuotePb {

  float bid = 1;
  float ask = 2;
}

message TradePb {
   
    string ts = 1;
    string symbol = 2;
    SecurityTypePb security_type = 3;
    float price = 4;
    float price_underlying = 5;
}

message QuotePb {
   
    string ts = 1;
    string symbol = 2;
    SecurityTypePb security_type = 3;
    float bid = 4;
    float ask = 5;
    float price_underlying = 6;
    
}

message QuotesPb {

    string symbol = 1;
    SecurityTypePb security_type = 2;
    repeated QuotePb quotes = 3;
}

message TradesPb {

    string symbol = 1;
    SecurityTypePb security_type = 2;
    repeated TradePb trades = 3;
}

message MarketDataHistoryPb {

    string ts = 1;
    string ts_start = 2;
    string ts_end = 3;
    string underlying = 4;
    map<string, QuotesPb> quotes = 5;
    map<string, TradesPb> trades = 6;
}

enum OptionRightPb {

    CALL = 0;
    PUT = 1;
}

enum SecurityTypePb {

    EQUITY = 0;
    OPTION = 1;
}

message MarketDataSnapByUnderlyingPb {

  string ts = 1;
  string underlying = 2;
  float underlying_price = 3;
  map<string, OptionQuotePb> option_quotes = 4;
}

message VectorDoublePb
{
    repeated double values = 1;    
}
