// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: PfRiskScenarios.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021, 8981
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace QuantConnect.Algorithm.CSharp.Core.IO {

  /// <summary>Holder for reflection information generated from PfRiskScenarios.proto</summary>
  public static partial class PfRiskScenariosReflection {

    #region Descriptor
    /// <summary>File descriptor for PfRiskScenarios.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static PfRiskScenariosReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "ChVQZlJpc2tTY2VuYXJpb3MucHJvdG8SJVF1YW50Q29ubmVjdC5BbGdvcml0",
            "aG0uQ1NoYXJwLkNvcmUuSU8aDENvbW1vbi5wcm90bxocUmVxdWVzdFNTVklD",
            "YWxpYnJhdGlvbi5wcm90byLxBAoOUGZSaXNrU2NlbmFyaW8SEgoKdW5kZXJs",
            "eWluZxgBIAEoCRJgCg5ob2xkaW5nc19oZWRnZRgCIAMoCzJILlF1YW50Q29u",
            "bmVjdC5BbGdvcml0aG0uQ1NoYXJwLkNvcmUuSU8uUGZSaXNrU2NlbmFyaW8u",
            "SG9sZGluZ3NIZWRnZUVudHJ5EgsKA2RQTBgDIAEoARINCgVzY29yZRgEIAEo",
            "ARITCgtkUExFcUhlZGdlZBgFIAEoARJUCghpdl9lbnRlchgGIAMoCzJCLlF1",
            "YW50Q29ubmVjdC5BbGdvcml0aG0uQ1NoYXJwLkNvcmUuSU8uUGZSaXNrU2Nl",
            "bmFyaW8uSXZFbnRlckVudHJ5EmQKEGhvbGRpbmdzX2N1cnJlbnQYByADKAsy",
            "Si5RdWFudENvbm5lY3QuQWxnb3JpdGhtLkNTaGFycC5Db3JlLklPLlBmUmlz",
            "a1NjZW5hcmlvLkhvbGRpbmdzQ3VycmVudEVudHJ5GmQKEkhvbGRpbmdzSGVk",
            "Z2VFbnRyeRILCgNrZXkYASABKAkSPQoFdmFsdWUYAiABKAsyLi5RdWFudENv",
            "bm5lY3QuQWxnb3JpdGhtLkNTaGFycC5Db3JlLklPLkhvbGRpbmc6AjgBGi4K",
            "DEl2RW50ZXJFbnRyeRILCgNrZXkYASABKAkSDQoFdmFsdWUYAiABKAE6AjgB",
            "GmYKFEhvbGRpbmdzQ3VycmVudEVudHJ5EgsKA2tleRgBIAEoCRI9CgV2YWx1",
            "ZRgCIAEoCzIuLlF1YW50Q29ubmVjdC5BbGdvcml0aG0uQ1NoYXJwLkNvcmUu",
            "SU8uSG9sZGluZzoCOAEisQMKFlJlcXVlc3RQZlJpc2tTY2VuYXJpb3MSCgoC",
            "dHMYASABKAkSEgoKdW5kZXJseWluZxgCIAEoCRJdCghob2xkaW5ncxgDIAMo",
            "CzJLLlF1YW50Q29ubmVjdC5BbGdvcml0aG0uQ1NoYXJwLkNvcmUuSU8uUmVx",
            "dWVzdFBmUmlza1NjZW5hcmlvcy5Ib2xkaW5nc0VudHJ5ElwKEW1hcmtldF9k",
            "YXRhX3NuYXBzGAQgAygLMkEuUXVhbnRDb25uZWN0LkFsZ29yaXRobS5DU2hh",
            "cnAuQ29yZS5JTy5NYXJrZXREYXRhU25hcEJ5VW5kZXJseWluZxJBCgZwYXJh",
            "bXMYBSADKAsyMS5RdWFudENvbm5lY3QuQWxnb3JpdGhtLkNTaGFycC5Db3Jl",
            "LklPLlNTVklQYXJhbXMSFgoOc2NvcGVkX3N5bWJvbHMYBiADKAkaXwoNSG9s",
            "ZGluZ3NFbnRyeRILCgNrZXkYASABKAkSPQoFdmFsdWUYAiABKAsyLi5RdWFu",
            "dENvbm5lY3QuQWxnb3JpdGhtLkNTaGFycC5Db3JlLklPLkhvbGRpbmc6AjgB",
            "IosBChdSZXNwb25zZVBmUmlza1NjZW5hcmlvcxIKCgJ0cxgBIAEoCRISCgp1",
            "bmRlcmx5aW5nGAIgASgJElAKEXBmX3Jpc2tfc2NlbmFyaW9zGAMgAygLMjUu",
            "UXVhbnRDb25uZWN0LkFsZ29yaXRobS5DU2hhcnAuQ29yZS5JTy5QZlJpc2tT",
            "Y2VuYXJpb0IoqgIlUXVhbnRDb25uZWN0LkFsZ29yaXRobS5DU2hhcnAuQ29y",
            "ZS5JT2IGcHJvdG8z"));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { global::QuantConnect.Algorithm.CSharp.Core.IO.CommonReflection.Descriptor, global::QuantConnect.Algorithm.CSharp.Core.IO.RequestSSVICalibrationReflection.Descriptor, },
          new pbr::GeneratedClrTypeInfo(null, null, new pbr::GeneratedClrTypeInfo[] {
            new pbr::GeneratedClrTypeInfo(typeof(global::QuantConnect.Algorithm.CSharp.Core.IO.PfRiskScenario), global::QuantConnect.Algorithm.CSharp.Core.IO.PfRiskScenario.Parser, new[]{ "Underlying", "HoldingsHedge", "DPL", "Score", "DPLEqHedged", "IvEnter", "HoldingsCurrent" }, null, null, null, new pbr::GeneratedClrTypeInfo[] { null, null, null, }),
            new pbr::GeneratedClrTypeInfo(typeof(global::QuantConnect.Algorithm.CSharp.Core.IO.RequestPfRiskScenarios), global::QuantConnect.Algorithm.CSharp.Core.IO.RequestPfRiskScenarios.Parser, new[]{ "Ts", "Underlying", "Holdings", "MarketDataSnaps", "Params", "ScopedSymbols" }, null, null, null, new pbr::GeneratedClrTypeInfo[] { null, }),
            new pbr::GeneratedClrTypeInfo(typeof(global::QuantConnect.Algorithm.CSharp.Core.IO.ResponsePfRiskScenarios), global::QuantConnect.Algorithm.CSharp.Core.IO.ResponsePfRiskScenarios.Parser, new[]{ "Ts", "Underlying", "PfRiskScenarios" }, null, null, null, null)
          }));
    }
    #endregion

  }
  #region Messages
  [global::System.Diagnostics.DebuggerDisplayAttribute("{ToString(),nq}")]
  public sealed partial class PfRiskScenario : pb::IMessage<PfRiskScenario>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<PfRiskScenario> _parser = new pb::MessageParser<PfRiskScenario>(() => new PfRiskScenario());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<PfRiskScenario> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::QuantConnect.Algorithm.CSharp.Core.IO.PfRiskScenariosReflection.Descriptor.MessageTypes[0]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public PfRiskScenario() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public PfRiskScenario(PfRiskScenario other) : this() {
      underlying_ = other.underlying_;
      holdingsHedge_ = other.holdingsHedge_.Clone();
      dPL_ = other.dPL_;
      score_ = other.score_;
      dPLEqHedged_ = other.dPLEqHedged_;
      ivEnter_ = other.ivEnter_.Clone();
      holdingsCurrent_ = other.holdingsCurrent_.Clone();
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public PfRiskScenario Clone() {
      return new PfRiskScenario(this);
    }

    /// <summary>Field number for the "underlying" field.</summary>
    public const int UnderlyingFieldNumber = 1;
    private string underlying_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string Underlying {
      get { return underlying_; }
      set {
        underlying_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "holdings_hedge" field.</summary>
    public const int HoldingsHedgeFieldNumber = 2;
    private static readonly pbc::MapField<string, global::QuantConnect.Algorithm.CSharp.Core.IO.Holding>.Codec _map_holdingsHedge_codec
        = new pbc::MapField<string, global::QuantConnect.Algorithm.CSharp.Core.IO.Holding>.Codec(pb::FieldCodec.ForString(10, ""), pb::FieldCodec.ForMessage(18, global::QuantConnect.Algorithm.CSharp.Core.IO.Holding.Parser), 18);
    private readonly pbc::MapField<string, global::QuantConnect.Algorithm.CSharp.Core.IO.Holding> holdingsHedge_ = new pbc::MapField<string, global::QuantConnect.Algorithm.CSharp.Core.IO.Holding>();
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public pbc::MapField<string, global::QuantConnect.Algorithm.CSharp.Core.IO.Holding> HoldingsHedge {
      get { return holdingsHedge_; }
    }

    /// <summary>Field number for the "dPL" field.</summary>
    public const int DPLFieldNumber = 3;
    private double dPL_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public double DPL {
      get { return dPL_; }
      set {
        dPL_ = value;
      }
    }

    /// <summary>Field number for the "score" field.</summary>
    public const int ScoreFieldNumber = 4;
    private double score_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public double Score {
      get { return score_; }
      set {
        score_ = value;
      }
    }

    /// <summary>Field number for the "dPLEqHedged" field.</summary>
    public const int DPLEqHedgedFieldNumber = 5;
    private double dPLEqHedged_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public double DPLEqHedged {
      get { return dPLEqHedged_; }
      set {
        dPLEqHedged_ = value;
      }
    }

    /// <summary>Field number for the "iv_enter" field.</summary>
    public const int IvEnterFieldNumber = 6;
    private static readonly pbc::MapField<string, double>.Codec _map_ivEnter_codec
        = new pbc::MapField<string, double>.Codec(pb::FieldCodec.ForString(10, ""), pb::FieldCodec.ForDouble(17, 0D), 50);
    private readonly pbc::MapField<string, double> ivEnter_ = new pbc::MapField<string, double>();
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public pbc::MapField<string, double> IvEnter {
      get { return ivEnter_; }
    }

    /// <summary>Field number for the "holdings_current" field.</summary>
    public const int HoldingsCurrentFieldNumber = 7;
    private static readonly pbc::MapField<string, global::QuantConnect.Algorithm.CSharp.Core.IO.Holding>.Codec _map_holdingsCurrent_codec
        = new pbc::MapField<string, global::QuantConnect.Algorithm.CSharp.Core.IO.Holding>.Codec(pb::FieldCodec.ForString(10, ""), pb::FieldCodec.ForMessage(18, global::QuantConnect.Algorithm.CSharp.Core.IO.Holding.Parser), 58);
    private readonly pbc::MapField<string, global::QuantConnect.Algorithm.CSharp.Core.IO.Holding> holdingsCurrent_ = new pbc::MapField<string, global::QuantConnect.Algorithm.CSharp.Core.IO.Holding>();
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public pbc::MapField<string, global::QuantConnect.Algorithm.CSharp.Core.IO.Holding> HoldingsCurrent {
      get { return holdingsCurrent_; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as PfRiskScenario);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(PfRiskScenario other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (Underlying != other.Underlying) return false;
      if (!HoldingsHedge.Equals(other.HoldingsHedge)) return false;
      if (!pbc::ProtobufEqualityComparers.BitwiseDoubleEqualityComparer.Equals(DPL, other.DPL)) return false;
      if (!pbc::ProtobufEqualityComparers.BitwiseDoubleEqualityComparer.Equals(Score, other.Score)) return false;
      if (!pbc::ProtobufEqualityComparers.BitwiseDoubleEqualityComparer.Equals(DPLEqHedged, other.DPLEqHedged)) return false;
      if (!IvEnter.Equals(other.IvEnter)) return false;
      if (!HoldingsCurrent.Equals(other.HoldingsCurrent)) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (Underlying.Length != 0) hash ^= Underlying.GetHashCode();
      hash ^= HoldingsHedge.GetHashCode();
      if (DPL != 0D) hash ^= pbc::ProtobufEqualityComparers.BitwiseDoubleEqualityComparer.GetHashCode(DPL);
      if (Score != 0D) hash ^= pbc::ProtobufEqualityComparers.BitwiseDoubleEqualityComparer.GetHashCode(Score);
      if (DPLEqHedged != 0D) hash ^= pbc::ProtobufEqualityComparers.BitwiseDoubleEqualityComparer.GetHashCode(DPLEqHedged);
      hash ^= IvEnter.GetHashCode();
      hash ^= HoldingsCurrent.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (Underlying.Length != 0) {
        output.WriteRawTag(10);
        output.WriteString(Underlying);
      }
      holdingsHedge_.WriteTo(output, _map_holdingsHedge_codec);
      if (DPL != 0D) {
        output.WriteRawTag(25);
        output.WriteDouble(DPL);
      }
      if (Score != 0D) {
        output.WriteRawTag(33);
        output.WriteDouble(Score);
      }
      if (DPLEqHedged != 0D) {
        output.WriteRawTag(41);
        output.WriteDouble(DPLEqHedged);
      }
      ivEnter_.WriteTo(output, _map_ivEnter_codec);
      holdingsCurrent_.WriteTo(output, _map_holdingsCurrent_codec);
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (Underlying.Length != 0) {
        output.WriteRawTag(10);
        output.WriteString(Underlying);
      }
      holdingsHedge_.WriteTo(ref output, _map_holdingsHedge_codec);
      if (DPL != 0D) {
        output.WriteRawTag(25);
        output.WriteDouble(DPL);
      }
      if (Score != 0D) {
        output.WriteRawTag(33);
        output.WriteDouble(Score);
      }
      if (DPLEqHedged != 0D) {
        output.WriteRawTag(41);
        output.WriteDouble(DPLEqHedged);
      }
      ivEnter_.WriteTo(ref output, _map_ivEnter_codec);
      holdingsCurrent_.WriteTo(ref output, _map_holdingsCurrent_codec);
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (Underlying.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Underlying);
      }
      size += holdingsHedge_.CalculateSize(_map_holdingsHedge_codec);
      if (DPL != 0D) {
        size += 1 + 8;
      }
      if (Score != 0D) {
        size += 1 + 8;
      }
      if (DPLEqHedged != 0D) {
        size += 1 + 8;
      }
      size += ivEnter_.CalculateSize(_map_ivEnter_codec);
      size += holdingsCurrent_.CalculateSize(_map_holdingsCurrent_codec);
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(PfRiskScenario other) {
      if (other == null) {
        return;
      }
      if (other.Underlying.Length != 0) {
        Underlying = other.Underlying;
      }
      holdingsHedge_.MergeFrom(other.holdingsHedge_);
      if (other.DPL != 0D) {
        DPL = other.DPL;
      }
      if (other.Score != 0D) {
        Score = other.Score;
      }
      if (other.DPLEqHedged != 0D) {
        DPLEqHedged = other.DPLEqHedged;
      }
      ivEnter_.MergeFrom(other.ivEnter_);
      holdingsCurrent_.MergeFrom(other.holdingsCurrent_);
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            Underlying = input.ReadString();
            break;
          }
          case 18: {
            holdingsHedge_.AddEntriesFrom(input, _map_holdingsHedge_codec);
            break;
          }
          case 25: {
            DPL = input.ReadDouble();
            break;
          }
          case 33: {
            Score = input.ReadDouble();
            break;
          }
          case 41: {
            DPLEqHedged = input.ReadDouble();
            break;
          }
          case 50: {
            ivEnter_.AddEntriesFrom(input, _map_ivEnter_codec);
            break;
          }
          case 58: {
            holdingsCurrent_.AddEntriesFrom(input, _map_holdingsCurrent_codec);
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 10: {
            Underlying = input.ReadString();
            break;
          }
          case 18: {
            holdingsHedge_.AddEntriesFrom(ref input, _map_holdingsHedge_codec);
            break;
          }
          case 25: {
            DPL = input.ReadDouble();
            break;
          }
          case 33: {
            Score = input.ReadDouble();
            break;
          }
          case 41: {
            DPLEqHedged = input.ReadDouble();
            break;
          }
          case 50: {
            ivEnter_.AddEntriesFrom(ref input, _map_ivEnter_codec);
            break;
          }
          case 58: {
            holdingsCurrent_.AddEntriesFrom(ref input, _map_holdingsCurrent_codec);
            break;
          }
        }
      }
    }
    #endif

  }

  [global::System.Diagnostics.DebuggerDisplayAttribute("{ToString(),nq}")]
  public sealed partial class RequestPfRiskScenarios : pb::IMessage<RequestPfRiskScenarios>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<RequestPfRiskScenarios> _parser = new pb::MessageParser<RequestPfRiskScenarios>(() => new RequestPfRiskScenarios());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<RequestPfRiskScenarios> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::QuantConnect.Algorithm.CSharp.Core.IO.PfRiskScenariosReflection.Descriptor.MessageTypes[1]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public RequestPfRiskScenarios() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public RequestPfRiskScenarios(RequestPfRiskScenarios other) : this() {
      ts_ = other.ts_;
      underlying_ = other.underlying_;
      holdings_ = other.holdings_.Clone();
      marketDataSnaps_ = other.marketDataSnaps_.Clone();
      params_ = other.params_.Clone();
      scopedSymbols_ = other.scopedSymbols_.Clone();
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public RequestPfRiskScenarios Clone() {
      return new RequestPfRiskScenarios(this);
    }

    /// <summary>Field number for the "ts" field.</summary>
    public const int TsFieldNumber = 1;
    private string ts_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string Ts {
      get { return ts_; }
      set {
        ts_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "underlying" field.</summary>
    public const int UnderlyingFieldNumber = 2;
    private string underlying_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string Underlying {
      get { return underlying_; }
      set {
        underlying_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "holdings" field.</summary>
    public const int HoldingsFieldNumber = 3;
    private static readonly pbc::MapField<string, global::QuantConnect.Algorithm.CSharp.Core.IO.Holding>.Codec _map_holdings_codec
        = new pbc::MapField<string, global::QuantConnect.Algorithm.CSharp.Core.IO.Holding>.Codec(pb::FieldCodec.ForString(10, ""), pb::FieldCodec.ForMessage(18, global::QuantConnect.Algorithm.CSharp.Core.IO.Holding.Parser), 26);
    private readonly pbc::MapField<string, global::QuantConnect.Algorithm.CSharp.Core.IO.Holding> holdings_ = new pbc::MapField<string, global::QuantConnect.Algorithm.CSharp.Core.IO.Holding>();
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public pbc::MapField<string, global::QuantConnect.Algorithm.CSharp.Core.IO.Holding> Holdings {
      get { return holdings_; }
    }

    /// <summary>Field number for the "market_data_snaps" field.</summary>
    public const int MarketDataSnapsFieldNumber = 4;
    private static readonly pb::FieldCodec<global::QuantConnect.Algorithm.CSharp.Core.IO.MarketDataSnapByUnderlying> _repeated_marketDataSnaps_codec
        = pb::FieldCodec.ForMessage(34, global::QuantConnect.Algorithm.CSharp.Core.IO.MarketDataSnapByUnderlying.Parser);
    private readonly pbc::RepeatedField<global::QuantConnect.Algorithm.CSharp.Core.IO.MarketDataSnapByUnderlying> marketDataSnaps_ = new pbc::RepeatedField<global::QuantConnect.Algorithm.CSharp.Core.IO.MarketDataSnapByUnderlying>();
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public pbc::RepeatedField<global::QuantConnect.Algorithm.CSharp.Core.IO.MarketDataSnapByUnderlying> MarketDataSnaps {
      get { return marketDataSnaps_; }
    }

    /// <summary>Field number for the "params" field.</summary>
    public const int ParamsFieldNumber = 5;
    private static readonly pb::FieldCodec<global::QuantConnect.Algorithm.CSharp.Core.IO.SSVIParams> _repeated_params_codec
        = pb::FieldCodec.ForMessage(42, global::QuantConnect.Algorithm.CSharp.Core.IO.SSVIParams.Parser);
    private readonly pbc::RepeatedField<global::QuantConnect.Algorithm.CSharp.Core.IO.SSVIParams> params_ = new pbc::RepeatedField<global::QuantConnect.Algorithm.CSharp.Core.IO.SSVIParams>();
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public pbc::RepeatedField<global::QuantConnect.Algorithm.CSharp.Core.IO.SSVIParams> Params {
      get { return params_; }
    }

    /// <summary>Field number for the "scoped_symbols" field.</summary>
    public const int ScopedSymbolsFieldNumber = 6;
    private static readonly pb::FieldCodec<string> _repeated_scopedSymbols_codec
        = pb::FieldCodec.ForString(50);
    private readonly pbc::RepeatedField<string> scopedSymbols_ = new pbc::RepeatedField<string>();
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public pbc::RepeatedField<string> ScopedSymbols {
      get { return scopedSymbols_; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as RequestPfRiskScenarios);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(RequestPfRiskScenarios other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (Ts != other.Ts) return false;
      if (Underlying != other.Underlying) return false;
      if (!Holdings.Equals(other.Holdings)) return false;
      if(!marketDataSnaps_.Equals(other.marketDataSnaps_)) return false;
      if(!params_.Equals(other.params_)) return false;
      if(!scopedSymbols_.Equals(other.scopedSymbols_)) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (Ts.Length != 0) hash ^= Ts.GetHashCode();
      if (Underlying.Length != 0) hash ^= Underlying.GetHashCode();
      hash ^= Holdings.GetHashCode();
      hash ^= marketDataSnaps_.GetHashCode();
      hash ^= params_.GetHashCode();
      hash ^= scopedSymbols_.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (Ts.Length != 0) {
        output.WriteRawTag(10);
        output.WriteString(Ts);
      }
      if (Underlying.Length != 0) {
        output.WriteRawTag(18);
        output.WriteString(Underlying);
      }
      holdings_.WriteTo(output, _map_holdings_codec);
      marketDataSnaps_.WriteTo(output, _repeated_marketDataSnaps_codec);
      params_.WriteTo(output, _repeated_params_codec);
      scopedSymbols_.WriteTo(output, _repeated_scopedSymbols_codec);
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (Ts.Length != 0) {
        output.WriteRawTag(10);
        output.WriteString(Ts);
      }
      if (Underlying.Length != 0) {
        output.WriteRawTag(18);
        output.WriteString(Underlying);
      }
      holdings_.WriteTo(ref output, _map_holdings_codec);
      marketDataSnaps_.WriteTo(ref output, _repeated_marketDataSnaps_codec);
      params_.WriteTo(ref output, _repeated_params_codec);
      scopedSymbols_.WriteTo(ref output, _repeated_scopedSymbols_codec);
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (Ts.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Ts);
      }
      if (Underlying.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Underlying);
      }
      size += holdings_.CalculateSize(_map_holdings_codec);
      size += marketDataSnaps_.CalculateSize(_repeated_marketDataSnaps_codec);
      size += params_.CalculateSize(_repeated_params_codec);
      size += scopedSymbols_.CalculateSize(_repeated_scopedSymbols_codec);
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(RequestPfRiskScenarios other) {
      if (other == null) {
        return;
      }
      if (other.Ts.Length != 0) {
        Ts = other.Ts;
      }
      if (other.Underlying.Length != 0) {
        Underlying = other.Underlying;
      }
      holdings_.MergeFrom(other.holdings_);
      marketDataSnaps_.Add(other.marketDataSnaps_);
      params_.Add(other.params_);
      scopedSymbols_.Add(other.scopedSymbols_);
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            Ts = input.ReadString();
            break;
          }
          case 18: {
            Underlying = input.ReadString();
            break;
          }
          case 26: {
            holdings_.AddEntriesFrom(input, _map_holdings_codec);
            break;
          }
          case 34: {
            marketDataSnaps_.AddEntriesFrom(input, _repeated_marketDataSnaps_codec);
            break;
          }
          case 42: {
            params_.AddEntriesFrom(input, _repeated_params_codec);
            break;
          }
          case 50: {
            scopedSymbols_.AddEntriesFrom(input, _repeated_scopedSymbols_codec);
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 10: {
            Ts = input.ReadString();
            break;
          }
          case 18: {
            Underlying = input.ReadString();
            break;
          }
          case 26: {
            holdings_.AddEntriesFrom(ref input, _map_holdings_codec);
            break;
          }
          case 34: {
            marketDataSnaps_.AddEntriesFrom(ref input, _repeated_marketDataSnaps_codec);
            break;
          }
          case 42: {
            params_.AddEntriesFrom(ref input, _repeated_params_codec);
            break;
          }
          case 50: {
            scopedSymbols_.AddEntriesFrom(ref input, _repeated_scopedSymbols_codec);
            break;
          }
        }
      }
    }
    #endif

  }

  [global::System.Diagnostics.DebuggerDisplayAttribute("{ToString(),nq}")]
  public sealed partial class ResponsePfRiskScenarios : pb::IMessage<ResponsePfRiskScenarios>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<ResponsePfRiskScenarios> _parser = new pb::MessageParser<ResponsePfRiskScenarios>(() => new ResponsePfRiskScenarios());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<ResponsePfRiskScenarios> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::QuantConnect.Algorithm.CSharp.Core.IO.PfRiskScenariosReflection.Descriptor.MessageTypes[2]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public ResponsePfRiskScenarios() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public ResponsePfRiskScenarios(ResponsePfRiskScenarios other) : this() {
      ts_ = other.ts_;
      underlying_ = other.underlying_;
      pfRiskScenarios_ = other.pfRiskScenarios_.Clone();
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public ResponsePfRiskScenarios Clone() {
      return new ResponsePfRiskScenarios(this);
    }

    /// <summary>Field number for the "ts" field.</summary>
    public const int TsFieldNumber = 1;
    private string ts_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string Ts {
      get { return ts_; }
      set {
        ts_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "underlying" field.</summary>
    public const int UnderlyingFieldNumber = 2;
    private string underlying_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string Underlying {
      get { return underlying_; }
      set {
        underlying_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "pf_risk_scenarios" field.</summary>
    public const int PfRiskScenariosFieldNumber = 3;
    private static readonly pb::FieldCodec<global::QuantConnect.Algorithm.CSharp.Core.IO.PfRiskScenario> _repeated_pfRiskScenarios_codec
        = pb::FieldCodec.ForMessage(26, global::QuantConnect.Algorithm.CSharp.Core.IO.PfRiskScenario.Parser);
    private readonly pbc::RepeatedField<global::QuantConnect.Algorithm.CSharp.Core.IO.PfRiskScenario> pfRiskScenarios_ = new pbc::RepeatedField<global::QuantConnect.Algorithm.CSharp.Core.IO.PfRiskScenario>();
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public pbc::RepeatedField<global::QuantConnect.Algorithm.CSharp.Core.IO.PfRiskScenario> PfRiskScenarios {
      get { return pfRiskScenarios_; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as ResponsePfRiskScenarios);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(ResponsePfRiskScenarios other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (Ts != other.Ts) return false;
      if (Underlying != other.Underlying) return false;
      if(!pfRiskScenarios_.Equals(other.pfRiskScenarios_)) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (Ts.Length != 0) hash ^= Ts.GetHashCode();
      if (Underlying.Length != 0) hash ^= Underlying.GetHashCode();
      hash ^= pfRiskScenarios_.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (Ts.Length != 0) {
        output.WriteRawTag(10);
        output.WriteString(Ts);
      }
      if (Underlying.Length != 0) {
        output.WriteRawTag(18);
        output.WriteString(Underlying);
      }
      pfRiskScenarios_.WriteTo(output, _repeated_pfRiskScenarios_codec);
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (Ts.Length != 0) {
        output.WriteRawTag(10);
        output.WriteString(Ts);
      }
      if (Underlying.Length != 0) {
        output.WriteRawTag(18);
        output.WriteString(Underlying);
      }
      pfRiskScenarios_.WriteTo(ref output, _repeated_pfRiskScenarios_codec);
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (Ts.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Ts);
      }
      if (Underlying.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Underlying);
      }
      size += pfRiskScenarios_.CalculateSize(_repeated_pfRiskScenarios_codec);
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(ResponsePfRiskScenarios other) {
      if (other == null) {
        return;
      }
      if (other.Ts.Length != 0) {
        Ts = other.Ts;
      }
      if (other.Underlying.Length != 0) {
        Underlying = other.Underlying;
      }
      pfRiskScenarios_.Add(other.pfRiskScenarios_);
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            Ts = input.ReadString();
            break;
          }
          case 18: {
            Underlying = input.ReadString();
            break;
          }
          case 26: {
            pfRiskScenarios_.AddEntriesFrom(input, _repeated_pfRiskScenarios_codec);
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 10: {
            Ts = input.ReadString();
            break;
          }
          case 18: {
            Underlying = input.ReadString();
            break;
          }
          case 26: {
            pfRiskScenarios_.AddEntriesFrom(ref input, _repeated_pfRiskScenarios_codec);
            break;
          }
        }
      }
    }
    #endif

  }

  #endregion

}

#endregion Designer generated code
