syntax = "proto3";

import "Common.proto";
import "RequestSSVICalibration.proto";

package QuantConnect.Algorithm.CSharp.Core.IO;

option csharp_namespace = "QuantConnect.Algorithm.CSharp.Core.IO";

message PfRiskScenarioPb {

  string underlying = 1;
  map<string, HoldingPb> holdings_hedge = 2;
  double dPL = 3;
  double score = 4;
  double dPLEqHedged = 5;
  map<string, double> iv_enter = 6;
  map<string, HoldingPb> holdings_current = 7;
}

message RequestPfRiskScenariosPb {

  string ts = 1;
  string underlying = 2;
  map<string, HoldingPb> holdings = 3;
  repeated MarketDataSnapByUnderlyingPb market_data_snaps = 4;
  repeated SSVIParamsPb params = 5;
  repeated string scoped_symbols = 6;
}

message ResponsePfRiskScenariosPb {

  string ts = 1;
  string underlying = 2;  
  repeated PfRiskScenarioPb pf_risk_scenarios = 3;
}

