syntax = "proto3";

import "Common.proto";
import "RequestSSVICalibration.proto";

package QuantConnect.Algorithm.CSharp.Core.IO;

option csharp_namespace = "QuantConnect.Algorithm.CSharp.Core.IO";


message RequestKalmanInitPb {

  string underlying = 1;
  string date_fit_start = 2;
  string date_fit_end = 3;
  string ts = 4;
}

message ResponseKalmanInitPb {

  string ts = 1;
  RequestKalmanInitPb request = 2;  
  repeated SSVIParamsPb init_state = 3;
  repeated VectorDoublePb init_covariance = 4;
}
