// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: RequestTargetPortfolios.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021, 8981
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace QuantConnect.Algorithm.CSharp.Core.IO {

  /// <summary>Holder for reflection information generated from RequestTargetPortfolios.proto</summary>
  public static partial class RequestTargetPortfoliosReflection {

    #region Descriptor
    /// <summary>File descriptor for RequestTargetPortfolios.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static RequestTargetPortfoliosReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "Ch1SZXF1ZXN0VGFyZ2V0UG9ydGZvbGlvcy5wcm90bxIlUXVhbnRDb25uZWN0",
            "LkFsZ29yaXRobS5DU2hhcnAuQ29yZS5JTxoMQ29tbW9uLnByb3RvGhJTdHJl",
            "c3NUZXN0RHMucHJvdG8aHFJlcXVlc3RTU1ZJQ2FsaWJyYXRpb24ucHJvdG8i",
            "zwMKEVRhcmdldFBvcnRmb2xpb1BiEhIKCnVuZGVybHlpbmcYASABKAkSWAoI",
            "aG9sZGluZ3MYAiADKAsyRi5RdWFudENvbm5lY3QuQWxnb3JpdGhtLkNTaGFy",
            "cC5Db3JlLklPLlRhcmdldFBvcnRmb2xpb1BiLkhvbGRpbmdzRW50cnkSEQoJ",
            "b2JqZWN0aXZlGAMgASgBEk4KA2l2cxgEIAMoCzJBLlF1YW50Q29ubmVjdC5B",
            "bGdvcml0aG0uQ1NoYXJwLkNvcmUuSU8uVGFyZ2V0UG9ydGZvbGlvUGIuSXZz",
            "RW50cnkSWgoVcmVzdWx0X3N0cmVzc190ZXN0X2RzGAUgASgLMjsuUXVhbnRD",
            "b25uZWN0LkFsZ29yaXRobS5DU2hhcnAuQ29yZS5JTy5SZXN1bHRTdHJlc3NU",
            "ZXN0RHNQYhphCg1Ib2xkaW5nc0VudHJ5EgsKA2tleRgBIAEoCRI/CgV2YWx1",
            "ZRgCIAEoCzIwLlF1YW50Q29ubmVjdC5BbGdvcml0aG0uQ1NoYXJwLkNvcmUu",
            "SU8uSG9sZGluZ1BiOgI4ARoqCghJdnNFbnRyeRILCgNrZXkYASABKAkSDQoF",
            "dmFsdWUYAiABKAE6AjgBItIDChlSZXF1ZXN0VGFyZ2V0UG9ydGZvbGlvc1Bi",
            "EgoKAnRzGAEgASgJEhIKCnVuZGVybHlpbmcYAiABKAkSYAoIaG9sZGluZ3MY",
            "AyADKAsyTi5RdWFudENvbm5lY3QuQWxnb3JpdGhtLkNTaGFycC5Db3JlLklP",
            "LlJlcXVlc3RUYXJnZXRQb3J0Zm9saW9zUGIuSG9sZGluZ3NFbnRyeRJeChFt",
            "YXJrZXRfZGF0YV9zbmFwcxgEIAMoCzJDLlF1YW50Q29ubmVjdC5BbGdvcml0",
            "aG0uQ1NoYXJwLkNvcmUuSU8uTWFya2V0RGF0YVNuYXBCeVVuZGVybHlpbmdQ",
            "YhITCgtuX2NvbnRyYWN0cxgFIAEoBRJDCgZwYXJhbXMYBiADKAsyMy5RdWFu",
            "dENvbm5lY3QuQWxnb3JpdGhtLkNTaGFycC5Db3JlLklPLlNTVklQYXJhbXNQ",
            "YhIWCg5zY29wZWRfc3ltYm9scxgHIAMoCRphCg1Ib2xkaW5nc0VudHJ5EgsK",
            "A2tleRgBIAEoCRI/CgV2YWx1ZRgCIAEoCzIwLlF1YW50Q29ubmVjdC5BbGdv",
            "cml0aG0uQ1NoYXJwLkNvcmUuSU8uSG9sZGluZ1BiOgI4ASKvAQoaUmVzcG9u",
            "c2VUYXJnZXRQb3J0Zm9saW9zUGISCgoCdHMYASABKAkSEgoKdW5kZXJseWlu",
            "ZxgCIAEoCRJTChF0YXJnZXRfcG9ydGZvbGlvcxgDIAMoCzI4LlF1YW50Q29u",
            "bmVjdC5BbGdvcml0aG0uQ1NoYXJwLkNvcmUuSU8uVGFyZ2V0UG9ydGZvbGlv",
            "UGISHAoUaXNfbGFzdF90cmFuc21pc3Npb24YBCABKAhCKKoCJVF1YW50Q29u",
            "bmVjdC5BbGdvcml0aG0uQ1NoYXJwLkNvcmUuSU9iBnByb3RvMw=="));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { global::QuantConnect.Algorithm.CSharp.Core.IO.CommonReflection.Descriptor, global::QuantConnect.Algorithm.CSharp.Core.IO.StressTestDsReflection.Descriptor, global::QuantConnect.Algorithm.CSharp.Core.IO.RequestSSVICalibrationReflection.Descriptor, },
          new pbr::GeneratedClrTypeInfo(null, null, new pbr::GeneratedClrTypeInfo[] {
            new pbr::GeneratedClrTypeInfo(typeof(global::QuantConnect.Algorithm.CSharp.Core.IO.TargetPortfolioPb), global::QuantConnect.Algorithm.CSharp.Core.IO.TargetPortfolioPb.Parser, new[]{ "Underlying", "Holdings", "Objective", "Ivs", "ResultStressTestDs" }, null, null, null, new pbr::GeneratedClrTypeInfo[] { null, null, }),
            new pbr::GeneratedClrTypeInfo(typeof(global::QuantConnect.Algorithm.CSharp.Core.IO.RequestTargetPortfoliosPb), global::QuantConnect.Algorithm.CSharp.Core.IO.RequestTargetPortfoliosPb.Parser, new[]{ "Ts", "Underlying", "Holdings", "MarketDataSnaps", "NContracts", "Params", "ScopedSymbols" }, null, null, null, new pbr::GeneratedClrTypeInfo[] { null, }),
            new pbr::GeneratedClrTypeInfo(typeof(global::QuantConnect.Algorithm.CSharp.Core.IO.ResponseTargetPortfoliosPb), global::QuantConnect.Algorithm.CSharp.Core.IO.ResponseTargetPortfoliosPb.Parser, new[]{ "Ts", "Underlying", "TargetPortfolios", "IsLastTransmission" }, null, null, null, null)
          }));
    }
    #endregion

  }
  #region Messages
  public sealed partial class TargetPortfolioPb : pb::IMessage<TargetPortfolioPb>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<TargetPortfolioPb> _parser = new pb::MessageParser<TargetPortfolioPb>(() => new TargetPortfolioPb());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<TargetPortfolioPb> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::QuantConnect.Algorithm.CSharp.Core.IO.RequestTargetPortfoliosReflection.Descriptor.MessageTypes[0]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public TargetPortfolioPb() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public TargetPortfolioPb(TargetPortfolioPb other) : this() {
      underlying_ = other.underlying_;
      holdings_ = other.holdings_.Clone();
      objective_ = other.objective_;
      ivs_ = other.ivs_.Clone();
      resultStressTestDs_ = other.resultStressTestDs_ != null ? other.resultStressTestDs_.Clone() : null;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public TargetPortfolioPb Clone() {
      return new TargetPortfolioPb(this);
    }

    /// <summary>Field number for the "underlying" field.</summary>
    public const int UnderlyingFieldNumber = 1;
    private string underlying_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string Underlying {
      get { return underlying_; }
      set {
        underlying_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "holdings" field.</summary>
    public const int HoldingsFieldNumber = 2;
    private static readonly pbc::MapField<string, global::QuantConnect.Algorithm.CSharp.Core.IO.HoldingPb>.Codec _map_holdings_codec
        = new pbc::MapField<string, global::QuantConnect.Algorithm.CSharp.Core.IO.HoldingPb>.Codec(pb::FieldCodec.ForString(10, ""), pb::FieldCodec.ForMessage(18, global::QuantConnect.Algorithm.CSharp.Core.IO.HoldingPb.Parser), 18);
    private readonly pbc::MapField<string, global::QuantConnect.Algorithm.CSharp.Core.IO.HoldingPb> holdings_ = new pbc::MapField<string, global::QuantConnect.Algorithm.CSharp.Core.IO.HoldingPb>();
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public pbc::MapField<string, global::QuantConnect.Algorithm.CSharp.Core.IO.HoldingPb> Holdings {
      get { return holdings_; }
    }

    /// <summary>Field number for the "objective" field.</summary>
    public const int ObjectiveFieldNumber = 3;
    private double objective_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public double Objective {
      get { return objective_; }
      set {
        objective_ = value;
      }
    }

    /// <summary>Field number for the "ivs" field.</summary>
    public const int IvsFieldNumber = 4;
    private static readonly pbc::MapField<string, double>.Codec _map_ivs_codec
        = new pbc::MapField<string, double>.Codec(pb::FieldCodec.ForString(10, ""), pb::FieldCodec.ForDouble(17, 0D), 34);
    private readonly pbc::MapField<string, double> ivs_ = new pbc::MapField<string, double>();
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public pbc::MapField<string, double> Ivs {
      get { return ivs_; }
    }

    /// <summary>Field number for the "result_stress_test_ds" field.</summary>
    public const int ResultStressTestDsFieldNumber = 5;
    private global::QuantConnect.Algorithm.CSharp.Core.IO.ResultStressTestDsPb resultStressTestDs_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::QuantConnect.Algorithm.CSharp.Core.IO.ResultStressTestDsPb ResultStressTestDs {
      get { return resultStressTestDs_; }
      set {
        resultStressTestDs_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as TargetPortfolioPb);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(TargetPortfolioPb other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (Underlying != other.Underlying) return false;
      if (!Holdings.Equals(other.Holdings)) return false;
      if (!pbc::ProtobufEqualityComparers.BitwiseDoubleEqualityComparer.Equals(Objective, other.Objective)) return false;
      if (!Ivs.Equals(other.Ivs)) return false;
      if (!object.Equals(ResultStressTestDs, other.ResultStressTestDs)) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (Underlying.Length != 0) hash ^= Underlying.GetHashCode();
      hash ^= Holdings.GetHashCode();
      if (Objective != 0D) hash ^= pbc::ProtobufEqualityComparers.BitwiseDoubleEqualityComparer.GetHashCode(Objective);
      hash ^= Ivs.GetHashCode();
      if (resultStressTestDs_ != null) hash ^= ResultStressTestDs.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (Underlying.Length != 0) {
        output.WriteRawTag(10);
        output.WriteString(Underlying);
      }
      holdings_.WriteTo(output, _map_holdings_codec);
      if (Objective != 0D) {
        output.WriteRawTag(25);
        output.WriteDouble(Objective);
      }
      ivs_.WriteTo(output, _map_ivs_codec);
      if (resultStressTestDs_ != null) {
        output.WriteRawTag(42);
        output.WriteMessage(ResultStressTestDs);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (Underlying.Length != 0) {
        output.WriteRawTag(10);
        output.WriteString(Underlying);
      }
      holdings_.WriteTo(ref output, _map_holdings_codec);
      if (Objective != 0D) {
        output.WriteRawTag(25);
        output.WriteDouble(Objective);
      }
      ivs_.WriteTo(ref output, _map_ivs_codec);
      if (resultStressTestDs_ != null) {
        output.WriteRawTag(42);
        output.WriteMessage(ResultStressTestDs);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (Underlying.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Underlying);
      }
      size += holdings_.CalculateSize(_map_holdings_codec);
      if (Objective != 0D) {
        size += 1 + 8;
      }
      size += ivs_.CalculateSize(_map_ivs_codec);
      if (resultStressTestDs_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(ResultStressTestDs);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(TargetPortfolioPb other) {
      if (other == null) {
        return;
      }
      if (other.Underlying.Length != 0) {
        Underlying = other.Underlying;
      }
      holdings_.Add(other.holdings_);
      if (other.Objective != 0D) {
        Objective = other.Objective;
      }
      ivs_.Add(other.ivs_);
      if (other.resultStressTestDs_ != null) {
        if (resultStressTestDs_ == null) {
          ResultStressTestDs = new global::QuantConnect.Algorithm.CSharp.Core.IO.ResultStressTestDsPb();
        }
        ResultStressTestDs.MergeFrom(other.ResultStressTestDs);
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            Underlying = input.ReadString();
            break;
          }
          case 18: {
            holdings_.AddEntriesFrom(input, _map_holdings_codec);
            break;
          }
          case 25: {
            Objective = input.ReadDouble();
            break;
          }
          case 34: {
            ivs_.AddEntriesFrom(input, _map_ivs_codec);
            break;
          }
          case 42: {
            if (resultStressTestDs_ == null) {
              ResultStressTestDs = new global::QuantConnect.Algorithm.CSharp.Core.IO.ResultStressTestDsPb();
            }
            input.ReadMessage(ResultStressTestDs);
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 10: {
            Underlying = input.ReadString();
            break;
          }
          case 18: {
            holdings_.AddEntriesFrom(ref input, _map_holdings_codec);
            break;
          }
          case 25: {
            Objective = input.ReadDouble();
            break;
          }
          case 34: {
            ivs_.AddEntriesFrom(ref input, _map_ivs_codec);
            break;
          }
          case 42: {
            if (resultStressTestDs_ == null) {
              ResultStressTestDs = new global::QuantConnect.Algorithm.CSharp.Core.IO.ResultStressTestDsPb();
            }
            input.ReadMessage(ResultStressTestDs);
            break;
          }
        }
      }
    }
    #endif

  }

  public sealed partial class RequestTargetPortfoliosPb : pb::IMessage<RequestTargetPortfoliosPb>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<RequestTargetPortfoliosPb> _parser = new pb::MessageParser<RequestTargetPortfoliosPb>(() => new RequestTargetPortfoliosPb());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<RequestTargetPortfoliosPb> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::QuantConnect.Algorithm.CSharp.Core.IO.RequestTargetPortfoliosReflection.Descriptor.MessageTypes[1]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public RequestTargetPortfoliosPb() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public RequestTargetPortfoliosPb(RequestTargetPortfoliosPb other) : this() {
      ts_ = other.ts_;
      underlying_ = other.underlying_;
      holdings_ = other.holdings_.Clone();
      marketDataSnaps_ = other.marketDataSnaps_.Clone();
      nContracts_ = other.nContracts_;
      params_ = other.params_.Clone();
      scopedSymbols_ = other.scopedSymbols_.Clone();
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public RequestTargetPortfoliosPb Clone() {
      return new RequestTargetPortfoliosPb(this);
    }

    /// <summary>Field number for the "ts" field.</summary>
    public const int TsFieldNumber = 1;
    private string ts_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string Ts {
      get { return ts_; }
      set {
        ts_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "underlying" field.</summary>
    public const int UnderlyingFieldNumber = 2;
    private string underlying_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string Underlying {
      get { return underlying_; }
      set {
        underlying_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "holdings" field.</summary>
    public const int HoldingsFieldNumber = 3;
    private static readonly pbc::MapField<string, global::QuantConnect.Algorithm.CSharp.Core.IO.HoldingPb>.Codec _map_holdings_codec
        = new pbc::MapField<string, global::QuantConnect.Algorithm.CSharp.Core.IO.HoldingPb>.Codec(pb::FieldCodec.ForString(10, ""), pb::FieldCodec.ForMessage(18, global::QuantConnect.Algorithm.CSharp.Core.IO.HoldingPb.Parser), 26);
    private readonly pbc::MapField<string, global::QuantConnect.Algorithm.CSharp.Core.IO.HoldingPb> holdings_ = new pbc::MapField<string, global::QuantConnect.Algorithm.CSharp.Core.IO.HoldingPb>();
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public pbc::MapField<string, global::QuantConnect.Algorithm.CSharp.Core.IO.HoldingPb> Holdings {
      get { return holdings_; }
    }

    /// <summary>Field number for the "market_data_snaps" field.</summary>
    public const int MarketDataSnapsFieldNumber = 4;
    private static readonly pb::FieldCodec<global::QuantConnect.Algorithm.CSharp.Core.IO.MarketDataSnapByUnderlyingPb> _repeated_marketDataSnaps_codec
        = pb::FieldCodec.ForMessage(34, global::QuantConnect.Algorithm.CSharp.Core.IO.MarketDataSnapByUnderlyingPb.Parser);
    private readonly pbc::RepeatedField<global::QuantConnect.Algorithm.CSharp.Core.IO.MarketDataSnapByUnderlyingPb> marketDataSnaps_ = new pbc::RepeatedField<global::QuantConnect.Algorithm.CSharp.Core.IO.MarketDataSnapByUnderlyingPb>();
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public pbc::RepeatedField<global::QuantConnect.Algorithm.CSharp.Core.IO.MarketDataSnapByUnderlyingPb> MarketDataSnaps {
      get { return marketDataSnaps_; }
    }

    /// <summary>Field number for the "n_contracts" field.</summary>
    public const int NContractsFieldNumber = 5;
    private int nContracts_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int NContracts {
      get { return nContracts_; }
      set {
        nContracts_ = value;
      }
    }

    /// <summary>Field number for the "params" field.</summary>
    public const int ParamsFieldNumber = 6;
    private static readonly pb::FieldCodec<global::QuantConnect.Algorithm.CSharp.Core.IO.SSVIParamsPb> _repeated_params_codec
        = pb::FieldCodec.ForMessage(50, global::QuantConnect.Algorithm.CSharp.Core.IO.SSVIParamsPb.Parser);
    private readonly pbc::RepeatedField<global::QuantConnect.Algorithm.CSharp.Core.IO.SSVIParamsPb> params_ = new pbc::RepeatedField<global::QuantConnect.Algorithm.CSharp.Core.IO.SSVIParamsPb>();
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public pbc::RepeatedField<global::QuantConnect.Algorithm.CSharp.Core.IO.SSVIParamsPb> Params {
      get { return params_; }
    }

    /// <summary>Field number for the "scoped_symbols" field.</summary>
    public const int ScopedSymbolsFieldNumber = 7;
    private static readonly pb::FieldCodec<string> _repeated_scopedSymbols_codec
        = pb::FieldCodec.ForString(58);
    private readonly pbc::RepeatedField<string> scopedSymbols_ = new pbc::RepeatedField<string>();
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public pbc::RepeatedField<string> ScopedSymbols {
      get { return scopedSymbols_; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as RequestTargetPortfoliosPb);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(RequestTargetPortfoliosPb other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (Ts != other.Ts) return false;
      if (Underlying != other.Underlying) return false;
      if (!Holdings.Equals(other.Holdings)) return false;
      if(!marketDataSnaps_.Equals(other.marketDataSnaps_)) return false;
      if (NContracts != other.NContracts) return false;
      if(!params_.Equals(other.params_)) return false;
      if(!scopedSymbols_.Equals(other.scopedSymbols_)) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (Ts.Length != 0) hash ^= Ts.GetHashCode();
      if (Underlying.Length != 0) hash ^= Underlying.GetHashCode();
      hash ^= Holdings.GetHashCode();
      hash ^= marketDataSnaps_.GetHashCode();
      if (NContracts != 0) hash ^= NContracts.GetHashCode();
      hash ^= params_.GetHashCode();
      hash ^= scopedSymbols_.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (Ts.Length != 0) {
        output.WriteRawTag(10);
        output.WriteString(Ts);
      }
      if (Underlying.Length != 0) {
        output.WriteRawTag(18);
        output.WriteString(Underlying);
      }
      holdings_.WriteTo(output, _map_holdings_codec);
      marketDataSnaps_.WriteTo(output, _repeated_marketDataSnaps_codec);
      if (NContracts != 0) {
        output.WriteRawTag(40);
        output.WriteInt32(NContracts);
      }
      params_.WriteTo(output, _repeated_params_codec);
      scopedSymbols_.WriteTo(output, _repeated_scopedSymbols_codec);
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (Ts.Length != 0) {
        output.WriteRawTag(10);
        output.WriteString(Ts);
      }
      if (Underlying.Length != 0) {
        output.WriteRawTag(18);
        output.WriteString(Underlying);
      }
      holdings_.WriteTo(ref output, _map_holdings_codec);
      marketDataSnaps_.WriteTo(ref output, _repeated_marketDataSnaps_codec);
      if (NContracts != 0) {
        output.WriteRawTag(40);
        output.WriteInt32(NContracts);
      }
      params_.WriteTo(ref output, _repeated_params_codec);
      scopedSymbols_.WriteTo(ref output, _repeated_scopedSymbols_codec);
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (Ts.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Ts);
      }
      if (Underlying.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Underlying);
      }
      size += holdings_.CalculateSize(_map_holdings_codec);
      size += marketDataSnaps_.CalculateSize(_repeated_marketDataSnaps_codec);
      if (NContracts != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(NContracts);
      }
      size += params_.CalculateSize(_repeated_params_codec);
      size += scopedSymbols_.CalculateSize(_repeated_scopedSymbols_codec);
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(RequestTargetPortfoliosPb other) {
      if (other == null) {
        return;
      }
      if (other.Ts.Length != 0) {
        Ts = other.Ts;
      }
      if (other.Underlying.Length != 0) {
        Underlying = other.Underlying;
      }
      holdings_.Add(other.holdings_);
      marketDataSnaps_.Add(other.marketDataSnaps_);
      if (other.NContracts != 0) {
        NContracts = other.NContracts;
      }
      params_.Add(other.params_);
      scopedSymbols_.Add(other.scopedSymbols_);
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            Ts = input.ReadString();
            break;
          }
          case 18: {
            Underlying = input.ReadString();
            break;
          }
          case 26: {
            holdings_.AddEntriesFrom(input, _map_holdings_codec);
            break;
          }
          case 34: {
            marketDataSnaps_.AddEntriesFrom(input, _repeated_marketDataSnaps_codec);
            break;
          }
          case 40: {
            NContracts = input.ReadInt32();
            break;
          }
          case 50: {
            params_.AddEntriesFrom(input, _repeated_params_codec);
            break;
          }
          case 58: {
            scopedSymbols_.AddEntriesFrom(input, _repeated_scopedSymbols_codec);
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 10: {
            Ts = input.ReadString();
            break;
          }
          case 18: {
            Underlying = input.ReadString();
            break;
          }
          case 26: {
            holdings_.AddEntriesFrom(ref input, _map_holdings_codec);
            break;
          }
          case 34: {
            marketDataSnaps_.AddEntriesFrom(ref input, _repeated_marketDataSnaps_codec);
            break;
          }
          case 40: {
            NContracts = input.ReadInt32();
            break;
          }
          case 50: {
            params_.AddEntriesFrom(ref input, _repeated_params_codec);
            break;
          }
          case 58: {
            scopedSymbols_.AddEntriesFrom(ref input, _repeated_scopedSymbols_codec);
            break;
          }
        }
      }
    }
    #endif

  }

  public sealed partial class ResponseTargetPortfoliosPb : pb::IMessage<ResponseTargetPortfoliosPb>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<ResponseTargetPortfoliosPb> _parser = new pb::MessageParser<ResponseTargetPortfoliosPb>(() => new ResponseTargetPortfoliosPb());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<ResponseTargetPortfoliosPb> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::QuantConnect.Algorithm.CSharp.Core.IO.RequestTargetPortfoliosReflection.Descriptor.MessageTypes[2]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public ResponseTargetPortfoliosPb() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public ResponseTargetPortfoliosPb(ResponseTargetPortfoliosPb other) : this() {
      ts_ = other.ts_;
      underlying_ = other.underlying_;
      targetPortfolios_ = other.targetPortfolios_.Clone();
      isLastTransmission_ = other.isLastTransmission_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public ResponseTargetPortfoliosPb Clone() {
      return new ResponseTargetPortfoliosPb(this);
    }

    /// <summary>Field number for the "ts" field.</summary>
    public const int TsFieldNumber = 1;
    private string ts_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string Ts {
      get { return ts_; }
      set {
        ts_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "underlying" field.</summary>
    public const int UnderlyingFieldNumber = 2;
    private string underlying_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string Underlying {
      get { return underlying_; }
      set {
        underlying_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "target_portfolios" field.</summary>
    public const int TargetPortfoliosFieldNumber = 3;
    private static readonly pb::FieldCodec<global::QuantConnect.Algorithm.CSharp.Core.IO.TargetPortfolioPb> _repeated_targetPortfolios_codec
        = pb::FieldCodec.ForMessage(26, global::QuantConnect.Algorithm.CSharp.Core.IO.TargetPortfolioPb.Parser);
    private readonly pbc::RepeatedField<global::QuantConnect.Algorithm.CSharp.Core.IO.TargetPortfolioPb> targetPortfolios_ = new pbc::RepeatedField<global::QuantConnect.Algorithm.CSharp.Core.IO.TargetPortfolioPb>();
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public pbc::RepeatedField<global::QuantConnect.Algorithm.CSharp.Core.IO.TargetPortfolioPb> TargetPortfolios {
      get { return targetPortfolios_; }
    }

    /// <summary>Field number for the "is_last_transmission" field.</summary>
    public const int IsLastTransmissionFieldNumber = 4;
    private bool isLastTransmission_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool IsLastTransmission {
      get { return isLastTransmission_; }
      set {
        isLastTransmission_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as ResponseTargetPortfoliosPb);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(ResponseTargetPortfoliosPb other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (Ts != other.Ts) return false;
      if (Underlying != other.Underlying) return false;
      if(!targetPortfolios_.Equals(other.targetPortfolios_)) return false;
      if (IsLastTransmission != other.IsLastTransmission) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (Ts.Length != 0) hash ^= Ts.GetHashCode();
      if (Underlying.Length != 0) hash ^= Underlying.GetHashCode();
      hash ^= targetPortfolios_.GetHashCode();
      if (IsLastTransmission != false) hash ^= IsLastTransmission.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (Ts.Length != 0) {
        output.WriteRawTag(10);
        output.WriteString(Ts);
      }
      if (Underlying.Length != 0) {
        output.WriteRawTag(18);
        output.WriteString(Underlying);
      }
      targetPortfolios_.WriteTo(output, _repeated_targetPortfolios_codec);
      if (IsLastTransmission != false) {
        output.WriteRawTag(32);
        output.WriteBool(IsLastTransmission);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (Ts.Length != 0) {
        output.WriteRawTag(10);
        output.WriteString(Ts);
      }
      if (Underlying.Length != 0) {
        output.WriteRawTag(18);
        output.WriteString(Underlying);
      }
      targetPortfolios_.WriteTo(ref output, _repeated_targetPortfolios_codec);
      if (IsLastTransmission != false) {
        output.WriteRawTag(32);
        output.WriteBool(IsLastTransmission);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (Ts.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Ts);
      }
      if (Underlying.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Underlying);
      }
      size += targetPortfolios_.CalculateSize(_repeated_targetPortfolios_codec);
      if (IsLastTransmission != false) {
        size += 1 + 1;
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(ResponseTargetPortfoliosPb other) {
      if (other == null) {
        return;
      }
      if (other.Ts.Length != 0) {
        Ts = other.Ts;
      }
      if (other.Underlying.Length != 0) {
        Underlying = other.Underlying;
      }
      targetPortfolios_.Add(other.targetPortfolios_);
      if (other.IsLastTransmission != false) {
        IsLastTransmission = other.IsLastTransmission;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            Ts = input.ReadString();
            break;
          }
          case 18: {
            Underlying = input.ReadString();
            break;
          }
          case 26: {
            targetPortfolios_.AddEntriesFrom(input, _repeated_targetPortfolios_codec);
            break;
          }
          case 32: {
            IsLastTransmission = input.ReadBool();
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 10: {
            Ts = input.ReadString();
            break;
          }
          case 18: {
            Underlying = input.ReadString();
            break;
          }
          case 26: {
            targetPortfolios_.AddEntriesFrom(ref input, _repeated_targetPortfolios_codec);
            break;
          }
          case 32: {
            IsLastTransmission = input.ReadBool();
            break;
          }
        }
      }
    }
    #endif

  }

  #endregion

}

#endregion Designer generated code
