syntax = "proto3";

import "Common.proto";
import "StressTestDs.proto";
import "RequestSSVICalibration.proto";

package QuantConnect.Algorithm.CSharp.Core.IO;

option csharp_namespace = "QuantConnect.Algorithm.CSharp.Core.IO";

message TargetPortfolioPb {

  string underlying = 1;
  map<string, HoldingPb> holdings = 2;
  double objective = 3;
  map<string, double> ivs = 4;
  ResultStressTestDsPb result_stress_test_ds = 5;
}

message RequestTargetPortfoliosPb {

  string ts = 1;
  string underlying = 2;
  map<string, HoldingPb> holdings = 3;  
  repeated MarketDataSnapByUnderlyingPb market_data_snaps = 4;
  int32 n_contracts = 5;
  repeated SSVIParamsPb params = 6;
  repeated string scoped_symbols = 7;
}

message ResponseTargetPortfoliosPb {

  string ts = 1;
  string underlying = 2;  
  repeated TargetPortfolioPb target_portfolios = 3;  
  bool is_last_transmission = 4;
}

