// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: RequestKalmanInit.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021, 8981
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace QuantConnect.Algorithm.CSharp.Core.IO {

  /// <summary>Holder for reflection information generated from RequestKalmanInit.proto</summary>
  public static partial class RequestKalmanInitReflection {

    #region Descriptor
    /// <summary>File descriptor for RequestKalmanInit.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static RequestKalmanInitReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "ChdSZXF1ZXN0S2FsbWFuSW5pdC5wcm90bxIlUXVhbnRDb25uZWN0LkFsZ29y",
            "aXRobS5DU2hhcnAuQ29yZS5JTxoMQ29tbW9uLnByb3RvItUBChFSZXF1ZXN0",
            "S2FsbWFuSW5pdBIKCgJ0cxgBIAEoCRISCgp1bmRlcmx5aW5nGAIgASgJEg4K",
            "BmV4cGlyeRgDIAEoCRJICgxvcHRpb25fcmlnaHQYBCABKA4yMi5RdWFudENv",
            "bm5lY3QuQWxnb3JpdGhtLkNTaGFycC5Db3JlLklPLk9wdGlvblJpZ2h0EhYK",
            "DmRhdGVfZml0X3N0YXJ0GAUgASgJEhQKDGRhdGVfZml0X2VuZBgGIAEoCRIY",
            "ChBzY29wZWRfbW9uZXluZXNzGAcgAygBIsEBChJSZXNwb25zZUthbG1hbklu",
            "aXQSSQoHcmVxdWVzdBgBIAEoCzI4LlF1YW50Q29ubmVjdC5BbGdvcml0aG0u",
            "Q1NoYXJwLkNvcmUuSU8uUmVxdWVzdEthbG1hbkluaXQSEgoKaW5pdF9zdGF0",
            "ZRgCIAMoARJMCg9pbml0X2NvdmFyaWFuY2UYAyADKAsyMy5RdWFudENvbm5l",
            "Y3QuQWxnb3JpdGhtLkNTaGFycC5Db3JlLklPLlZlY3RvckRvdWJsZUIoqgIl",
            "UXVhbnRDb25uZWN0LkFsZ29yaXRobS5DU2hhcnAuQ29yZS5JT2IGcHJvdG8z"));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { global::QuantConnect.Algorithm.CSharp.Core.IO.CommonReflection.Descriptor, },
          new pbr::GeneratedClrTypeInfo(null, null, new pbr::GeneratedClrTypeInfo[] {
            new pbr::GeneratedClrTypeInfo(typeof(global::QuantConnect.Algorithm.CSharp.Core.IO.RequestKalmanInit), global::QuantConnect.Algorithm.CSharp.Core.IO.RequestKalmanInit.Parser, new[]{ "Ts", "Underlying", "Expiry", "OptionRight", "DateFitStart", "DateFitEnd", "ScopedMoneyness" }, null, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::QuantConnect.Algorithm.CSharp.Core.IO.ResponseKalmanInit), global::QuantConnect.Algorithm.CSharp.Core.IO.ResponseKalmanInit.Parser, new[]{ "Request", "InitState", "InitCovariance" }, null, null, null, null)
          }));
    }
    #endregion

  }
  #region Messages
  [global::System.Diagnostics.DebuggerDisplayAttribute("{ToString(),nq}")]
  public sealed partial class RequestKalmanInit : pb::IMessage<RequestKalmanInit>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<RequestKalmanInit> _parser = new pb::MessageParser<RequestKalmanInit>(() => new RequestKalmanInit());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<RequestKalmanInit> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::QuantConnect.Algorithm.CSharp.Core.IO.RequestKalmanInitReflection.Descriptor.MessageTypes[0]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public RequestKalmanInit() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public RequestKalmanInit(RequestKalmanInit other) : this() {
      ts_ = other.ts_;
      underlying_ = other.underlying_;
      expiry_ = other.expiry_;
      optionRight_ = other.optionRight_;
      dateFitStart_ = other.dateFitStart_;
      dateFitEnd_ = other.dateFitEnd_;
      scopedMoneyness_ = other.scopedMoneyness_.Clone();
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public RequestKalmanInit Clone() {
      return new RequestKalmanInit(this);
    }

    /// <summary>Field number for the "ts" field.</summary>
    public const int TsFieldNumber = 1;
    private string ts_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string Ts {
      get { return ts_; }
      set {
        ts_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "underlying" field.</summary>
    public const int UnderlyingFieldNumber = 2;
    private string underlying_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string Underlying {
      get { return underlying_; }
      set {
        underlying_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "expiry" field.</summary>
    public const int ExpiryFieldNumber = 3;
    private string expiry_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string Expiry {
      get { return expiry_; }
      set {
        expiry_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "option_right" field.</summary>
    public const int OptionRightFieldNumber = 4;
    private global::QuantConnect.Algorithm.CSharp.Core.IO.OptionRight optionRight_ = global::QuantConnect.Algorithm.CSharp.Core.IO.OptionRight.Call;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::QuantConnect.Algorithm.CSharp.Core.IO.OptionRight OptionRight {
      get { return optionRight_; }
      set {
        optionRight_ = value;
      }
    }

    /// <summary>Field number for the "date_fit_start" field.</summary>
    public const int DateFitStartFieldNumber = 5;
    private string dateFitStart_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string DateFitStart {
      get { return dateFitStart_; }
      set {
        dateFitStart_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "date_fit_end" field.</summary>
    public const int DateFitEndFieldNumber = 6;
    private string dateFitEnd_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string DateFitEnd {
      get { return dateFitEnd_; }
      set {
        dateFitEnd_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "scoped_moneyness" field.</summary>
    public const int ScopedMoneynessFieldNumber = 7;
    private static readonly pb::FieldCodec<double> _repeated_scopedMoneyness_codec
        = pb::FieldCodec.ForDouble(58);
    private readonly pbc::RepeatedField<double> scopedMoneyness_ = new pbc::RepeatedField<double>();
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public pbc::RepeatedField<double> ScopedMoneyness {
      get { return scopedMoneyness_; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as RequestKalmanInit);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(RequestKalmanInit other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (Ts != other.Ts) return false;
      if (Underlying != other.Underlying) return false;
      if (Expiry != other.Expiry) return false;
      if (OptionRight != other.OptionRight) return false;
      if (DateFitStart != other.DateFitStart) return false;
      if (DateFitEnd != other.DateFitEnd) return false;
      if(!scopedMoneyness_.Equals(other.scopedMoneyness_)) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (Ts.Length != 0) hash ^= Ts.GetHashCode();
      if (Underlying.Length != 0) hash ^= Underlying.GetHashCode();
      if (Expiry.Length != 0) hash ^= Expiry.GetHashCode();
      if (OptionRight != global::QuantConnect.Algorithm.CSharp.Core.IO.OptionRight.Call) hash ^= OptionRight.GetHashCode();
      if (DateFitStart.Length != 0) hash ^= DateFitStart.GetHashCode();
      if (DateFitEnd.Length != 0) hash ^= DateFitEnd.GetHashCode();
      hash ^= scopedMoneyness_.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (Ts.Length != 0) {
        output.WriteRawTag(10);
        output.WriteString(Ts);
      }
      if (Underlying.Length != 0) {
        output.WriteRawTag(18);
        output.WriteString(Underlying);
      }
      if (Expiry.Length != 0) {
        output.WriteRawTag(26);
        output.WriteString(Expiry);
      }
      if (OptionRight != global::QuantConnect.Algorithm.CSharp.Core.IO.OptionRight.Call) {
        output.WriteRawTag(32);
        output.WriteEnum((int) OptionRight);
      }
      if (DateFitStart.Length != 0) {
        output.WriteRawTag(42);
        output.WriteString(DateFitStart);
      }
      if (DateFitEnd.Length != 0) {
        output.WriteRawTag(50);
        output.WriteString(DateFitEnd);
      }
      scopedMoneyness_.WriteTo(output, _repeated_scopedMoneyness_codec);
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (Ts.Length != 0) {
        output.WriteRawTag(10);
        output.WriteString(Ts);
      }
      if (Underlying.Length != 0) {
        output.WriteRawTag(18);
        output.WriteString(Underlying);
      }
      if (Expiry.Length != 0) {
        output.WriteRawTag(26);
        output.WriteString(Expiry);
      }
      if (OptionRight != global::QuantConnect.Algorithm.CSharp.Core.IO.OptionRight.Call) {
        output.WriteRawTag(32);
        output.WriteEnum((int) OptionRight);
      }
      if (DateFitStart.Length != 0) {
        output.WriteRawTag(42);
        output.WriteString(DateFitStart);
      }
      if (DateFitEnd.Length != 0) {
        output.WriteRawTag(50);
        output.WriteString(DateFitEnd);
      }
      scopedMoneyness_.WriteTo(ref output, _repeated_scopedMoneyness_codec);
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (Ts.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Ts);
      }
      if (Underlying.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Underlying);
      }
      if (Expiry.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Expiry);
      }
      if (OptionRight != global::QuantConnect.Algorithm.CSharp.Core.IO.OptionRight.Call) {
        size += 1 + pb::CodedOutputStream.ComputeEnumSize((int) OptionRight);
      }
      if (DateFitStart.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(DateFitStart);
      }
      if (DateFitEnd.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(DateFitEnd);
      }
      size += scopedMoneyness_.CalculateSize(_repeated_scopedMoneyness_codec);
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(RequestKalmanInit other) {
      if (other == null) {
        return;
      }
      if (other.Ts.Length != 0) {
        Ts = other.Ts;
      }
      if (other.Underlying.Length != 0) {
        Underlying = other.Underlying;
      }
      if (other.Expiry.Length != 0) {
        Expiry = other.Expiry;
      }
      if (other.OptionRight != global::QuantConnect.Algorithm.CSharp.Core.IO.OptionRight.Call) {
        OptionRight = other.OptionRight;
      }
      if (other.DateFitStart.Length != 0) {
        DateFitStart = other.DateFitStart;
      }
      if (other.DateFitEnd.Length != 0) {
        DateFitEnd = other.DateFitEnd;
      }
      scopedMoneyness_.Add(other.scopedMoneyness_);
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            Ts = input.ReadString();
            break;
          }
          case 18: {
            Underlying = input.ReadString();
            break;
          }
          case 26: {
            Expiry = input.ReadString();
            break;
          }
          case 32: {
            OptionRight = (global::QuantConnect.Algorithm.CSharp.Core.IO.OptionRight) input.ReadEnum();
            break;
          }
          case 42: {
            DateFitStart = input.ReadString();
            break;
          }
          case 50: {
            DateFitEnd = input.ReadString();
            break;
          }
          case 58:
          case 57: {
            scopedMoneyness_.AddEntriesFrom(input, _repeated_scopedMoneyness_codec);
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 10: {
            Ts = input.ReadString();
            break;
          }
          case 18: {
            Underlying = input.ReadString();
            break;
          }
          case 26: {
            Expiry = input.ReadString();
            break;
          }
          case 32: {
            OptionRight = (global::QuantConnect.Algorithm.CSharp.Core.IO.OptionRight) input.ReadEnum();
            break;
          }
          case 42: {
            DateFitStart = input.ReadString();
            break;
          }
          case 50: {
            DateFitEnd = input.ReadString();
            break;
          }
          case 58:
          case 57: {
            scopedMoneyness_.AddEntriesFrom(ref input, _repeated_scopedMoneyness_codec);
            break;
          }
        }
      }
    }
    #endif

  }

  [global::System.Diagnostics.DebuggerDisplayAttribute("{ToString(),nq}")]
  public sealed partial class ResponseKalmanInit : pb::IMessage<ResponseKalmanInit>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<ResponseKalmanInit> _parser = new pb::MessageParser<ResponseKalmanInit>(() => new ResponseKalmanInit());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<ResponseKalmanInit> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::QuantConnect.Algorithm.CSharp.Core.IO.RequestKalmanInitReflection.Descriptor.MessageTypes[1]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public ResponseKalmanInit() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public ResponseKalmanInit(ResponseKalmanInit other) : this() {
      request_ = other.request_ != null ? other.request_.Clone() : null;
      initState_ = other.initState_.Clone();
      initCovariance_ = other.initCovariance_.Clone();
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public ResponseKalmanInit Clone() {
      return new ResponseKalmanInit(this);
    }

    /// <summary>Field number for the "request" field.</summary>
    public const int RequestFieldNumber = 1;
    private global::QuantConnect.Algorithm.CSharp.Core.IO.RequestKalmanInit request_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::QuantConnect.Algorithm.CSharp.Core.IO.RequestKalmanInit Request {
      get { return request_; }
      set {
        request_ = value;
      }
    }

    /// <summary>Field number for the "init_state" field.</summary>
    public const int InitStateFieldNumber = 2;
    private static readonly pb::FieldCodec<double> _repeated_initState_codec
        = pb::FieldCodec.ForDouble(18);
    private readonly pbc::RepeatedField<double> initState_ = new pbc::RepeatedField<double>();
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public pbc::RepeatedField<double> InitState {
      get { return initState_; }
    }

    /// <summary>Field number for the "init_covariance" field.</summary>
    public const int InitCovarianceFieldNumber = 3;
    private static readonly pb::FieldCodec<global::QuantConnect.Algorithm.CSharp.Core.IO.VectorDouble> _repeated_initCovariance_codec
        = pb::FieldCodec.ForMessage(26, global::QuantConnect.Algorithm.CSharp.Core.IO.VectorDouble.Parser);
    private readonly pbc::RepeatedField<global::QuantConnect.Algorithm.CSharp.Core.IO.VectorDouble> initCovariance_ = new pbc::RepeatedField<global::QuantConnect.Algorithm.CSharp.Core.IO.VectorDouble>();
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public pbc::RepeatedField<global::QuantConnect.Algorithm.CSharp.Core.IO.VectorDouble> InitCovariance {
      get { return initCovariance_; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as ResponseKalmanInit);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(ResponseKalmanInit other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (!object.Equals(Request, other.Request)) return false;
      if(!initState_.Equals(other.initState_)) return false;
      if(!initCovariance_.Equals(other.initCovariance_)) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (request_ != null) hash ^= Request.GetHashCode();
      hash ^= initState_.GetHashCode();
      hash ^= initCovariance_.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (request_ != null) {
        output.WriteRawTag(10);
        output.WriteMessage(Request);
      }
      initState_.WriteTo(output, _repeated_initState_codec);
      initCovariance_.WriteTo(output, _repeated_initCovariance_codec);
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (request_ != null) {
        output.WriteRawTag(10);
        output.WriteMessage(Request);
      }
      initState_.WriteTo(ref output, _repeated_initState_codec);
      initCovariance_.WriteTo(ref output, _repeated_initCovariance_codec);
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (request_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(Request);
      }
      size += initState_.CalculateSize(_repeated_initState_codec);
      size += initCovariance_.CalculateSize(_repeated_initCovariance_codec);
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(ResponseKalmanInit other) {
      if (other == null) {
        return;
      }
      if (other.request_ != null) {
        if (request_ == null) {
          Request = new global::QuantConnect.Algorithm.CSharp.Core.IO.RequestKalmanInit();
        }
        Request.MergeFrom(other.Request);
      }
      initState_.Add(other.initState_);
      initCovariance_.Add(other.initCovariance_);
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            if (request_ == null) {
              Request = new global::QuantConnect.Algorithm.CSharp.Core.IO.RequestKalmanInit();
            }
            input.ReadMessage(Request);
            break;
          }
          case 18:
          case 17: {
            initState_.AddEntriesFrom(input, _repeated_initState_codec);
            break;
          }
          case 26: {
            initCovariance_.AddEntriesFrom(input, _repeated_initCovariance_codec);
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 10: {
            if (request_ == null) {
              Request = new global::QuantConnect.Algorithm.CSharp.Core.IO.RequestKalmanInit();
            }
            input.ReadMessage(Request);
            break;
          }
          case 18:
          case 17: {
            initState_.AddEntriesFrom(ref input, _repeated_initState_codec);
            break;
          }
          case 26: {
            initCovariance_.AddEntriesFrom(ref input, _repeated_initCovariance_codec);
            break;
          }
        }
      }
    }
    #endif

  }

  #endregion

}

#endregion Designer generated code
